name: Update and Modify Conf File

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_conf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch Upstream Changes
        run: |
          git remote add upstream https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever.git
          git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git merge upstream/release --allow-unrelated-histories --no-edit

      - name: Debug - List Root Directory
        run: |
          echo "Listing root directory contents..."
          ls -la

      - name: Debug - Find Conf File
        run: |
          echo "Searching for sr_backcn_ad.conf..."
          find . -name "sr_backcn_ad.conf"

      - name: Modify Conf File
        run: |
          CONF_PATH=$(find . -name "sr_backcn_ad.conf" | head -n 1)
          if [ -z "$CONF_PATH" ]; then
            echo "File sr_backcn_ad.conf not found!"
            exit 1
          else
            sed -i 's|dns-server = https://dns.alidns.com/dns-query, https://doh.pub/dns-query|dns-server = https://dns.alidns.com/dns-query, https://doh.pub/dns-query, 114.114.114.114, 8.8.8.8, 8.8.4.4, 1.1.1.1, 1.0.0.1, 9.9.9.9, 208.67.222.222, 208.67.220.220|g' "$CONF_PATH"
            cp "$CONF_PATH" "$(dirname $CONF_PATH)/sr_backcn_ad_mod.conf"
          fi

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Update and modify sr_backcn_ad.conf"
          git push origin main  # Change 'main' to your fork's branch name if needed
